### ISSUE TITLE
Please fix your app name and icon

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/pijar_food_mobile#1]
![WhatsApp Image 2023-08-07 at 21 38 07](https://github.com/nluthfis/pijar_food_mobile/assets/49361887/246f5d9d-459f-4fa6-9249-9c4a7c3b6c0f)

**Comment by nluthfis** [comment]
![Screenshot_20230808_015409_One_UI_Home](https://github.com/nluthfis/pijar_food_mobile/assets/42950482/59d64b28-1ab1-4be6-ad90-5612040645a6)
Done!
