### ISSUE TITLE
In my recipe if blank show placeholder

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/pijar_food_mobile#2]
![WhatsApp Image 2023-08-07 at 21 42 16](https://github.com/nluthfis/pijar_food_mobile/assets/49361887/7d60cb7a-b5d2-4149-9a06-d10b3943527e)
Add placeholder or alert in body with content like _recipe not found_

**Comment by nluthfis** [comment]
![image](https://github.com/nluthfis/pijar_food_mobile/assets/42950482/96ccef10-457d-42f6-b748-0e0410beec41)
Fixed!
