### ISSUE TITLE
Please fix add button label

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/pijar_food_mobile#3]
Fix label button add not ad..
![WhatsApp Image 2023-08-07 at 21 47 37](https://github.com/nluthfis/pijar_food_mobile/assets/49361887/c490a6d7-d6a4-4c4a-896a-ea20d101b357)

**Comment by nluthfis** [comment]
![image](https://github.com/nluthfis/pijar_food_mobile/assets/42950482/3edaa72c-3e6e-46e9-aa5c-87ad1b18609c) (on emulator device Pixel 4) 
![Screenshot_20230808_005934_pijar_food_mobile](https://github.com/nluthfis/pijar_food_mobile/assets/42950482/bf6c5c64-40b4-4b5b-b82c-db72adc8432a) (on real device samsung a72)
Fixed!
