### ISSUE TITLE
Change wording dislike to unlike

### ISSUE THREAD

**Issue by kubil-ismail** [nluthfis/pijar_food_mobile#4]
![WhatsApp Image 2023-08-07 at 21 48 57](https://github.com/nluthfis/pijar_food_mobile/assets/49361887/e4ce789f-871a-47e8-ba3c-b5761dfd6c03)

Please change wording dislike to unlike and change icon if already like fill icon hearth not just outline

**Comment by nluthfis** [comment]
![image](https://github.com/nluthfis/pijar_food_mobile/assets/42950482/97df42eb-6c29-4e14-9c82-10ba1a193015)
Done.. Fixed!
